from typing import Protocol


class Notifier(Protocol):
    async def info(self, text: str) -> None: ...
    async def progress(self, pct: int, text: str = "") -> None: ...
    async def error(self, text: str) -> None: ...
